### ISSUE TITLE
Add a config sub-command

### ISSUE THREAD

**Issue by scymtym** [RDTK/generator#1]
**Is your feature request related to a problem? Please describe.**
I'm sometimes not sure which configuration the generator is using and what configuration files it expects. The output of `build-generator help` does not talk about configuration files or the current configuration.

**Describe the solution you'd like**
It would be really helpful if there was a sub-command, for example `config`, for exploring configuration aspects:
```sh
$ build-generator config

Usage: build-generator [GLOBAL-OPTIONS] config …

Query the current configuration.

Configuration files are tried in the following order:
  1. $(pwd)/build-generator.conf
  2. ${HOME}/.config/build-generator.conf
…

$ build-generator config list
commands.generate.username = user
commands.generate.base-uri = https://localhost:8080
…
```

**Comment by scymtym** [comment]
@semeyerz Would something like this help?

**Comment by semeyerz** [comment]
Yes, that would be nice!
