### ISSUE TITLE
Better build from source instructions, update README

### ISSUE THREAD

**Issue by nexero** [RDTK/generator#13]
**Is your feature request related to a problem? Please describe.**
I'd like to build the `generator` from source like described in the `README.org`:
```sh
sbcl --no-userinit --load quicklisp/setup.lisp --eval '(asdf:make :jenkins.project.commandline-interface)'
```
But there is no `quicklisp/setup.lisp` in the repo, so maybe this is outdated?
Even the described dependencies should be pulled and built, so no further user interaction is required, more self-contained so to say.

By looking at the `.travis.yml` file, one can get a clearer view on the build process itself, but this should be described in the `README.org`, too. 

**Describe the solution you'd like**
Maybe this is against #2, but very comfortable for me:
```sh
mkdir build; cd build; cmake ..
```

**Comment by scymtym** [comment]
Please re-open if anything is still unclear or the instruction don't work.
