### ISSUE TITLE
aspect to control when downstream jobs should be build

### ISSUE THREAD

**Issue by rhaschke** [RDTK/generator#39]
I noticed that jenkins doesn't build downstream jobs anymore if the build is unstable.
Maybe the following options are new to jenkins:
![image](https://user-images.githubusercontent.com/5376030/64681351-d8846080-d47f-11e9-9bff-863e5af63627.png)

However, to ensure that my downstream jobs are build, even when an upstream one is unstable only, I need to set those options from the build-generator, based on the variable `orchestration.success-results`. Is there already a way to accomplish this?

**Comment by scymtym** [comment]
This is not yet supported. I'm adding a new variable `dependencies.required-upstream-result` to control this behavior.
