### ISSUE TITLE
New release for Ubuntu 20.04?

### ISSUE THREAD

**Issue by rhaschke** [RDTK/generator#48]
@scymtym
The latest version of build-generator (0.32) requires `libssl.so.1.0.0`. However, in Ubuntu 20.04, only libssl.so.1.1.0 is available. Hence, build-generator fails as follows:
```
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                    {10005984C3}>:
  Error opening shared object "libssl.so.1.0.0":
  libssl.so.1.0.0: cannot open shared object file: No such file or directory.

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10005984C3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." {1000E1D633}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." {1000E1D633}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." {1000E1D633}>)
3: (ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." "libssl.so.1.0.0" "libssl.so.1.0.0: cannot open shared object file: No such file or directory")
4: (SB-SYS:DLOPEN-OR-LOSE #S(SB-ALIEN::SHARED-OBJECT :PATHNAME #P"libssl.so.1.0.0" :NAMESTRING "libssl.so.1.0.0" :HANDLE NIL :DONT-SAVE NIL))
5: (SB-ALIEN::TRY-REOPEN-SHARED-OBJECT #S(SB-ALIEN::SHARED-OBJECT :PATHNAME #P"libssl.so.1.0.0" :NAMESTRING "libssl.so.1.0.0" :HANDLE NIL :DONT-SAVE NIL))
6: (SB-SYS:REOPEN-SHARED-OBJECTS)
7: (SB-IMPL::FOREIGN-REINIT)
8: (SB-IMPL::REINIT)
9: ((FLET SB-UNIX::BODY :IN SAVE-LISP-AND-DIE))
10: ((FLET "WITHOUT-INTERRUPTS-BODY-14" :IN SAVE-LISP-AND-DIE))
11: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))
```
Could you please prepare a release for Ubuntu 20.04 as well? Thanks.

**Comment by scymtym** [comment]
Before I attach a binary built in the usual way to the 0.32 release, you could try [this one](https://github.com/RDTK/generator/actions/runs/272690027). The latter is built using [GitHub actions](https://github.com/RDTK/generator/actions).

**Comment by rhaschke** [comment]
Thanks, this one works. As this is version 0.33.45, I guess it was built from `master` branch. I'm fine with this and don't need a 0.32 version for Focal. But it would be great to get a version supporting the `language-server` verb :wink:

**Comment by scymtym** [comment]
> But it would be great to get a version supporting the language-server verb wink

https://github.com/RDTK/generator/actions/runs/273159180 but untested.

**Comment by scymtym** [comment]
https://github.com/RDTK/generator/releases/tag/release-0.33
