### ISSUE TITLE
Install Jenkins broken

### ISSUE THREAD

**Issue by LeroyR** [RDTK/generator#49]
New Jenkins release does not work with the generator.

**Which generator version are you using?**

```sh
build-generator 0.33.63
asdf            3.3.1
SBCL            2.0.10.0.sbcl-2.0.10.0-badfc73b9
```

**What did you do?**

install-jenkins   

**What happened instead?**

- On login it redirects to a different port so you have to change the URL in your browser.
- Jenkins misses plugins, shows a first setup page to install default plugins. 

I also tried to set the jenkins-download-url to an older release but the generator seems to get stuck (no output after ~5minutes)

**Comment by scymtym** [comment]
Please try with the most recent commit in the master branch.

**Comment by LeroyR** [comment]
Jenkis installs fine and does not show the setup wizard :+1:
