### ISSUE TITLE
Deploy Failure

### ISSUE THREAD

**Issue by LeroyR** [RDTK/generator#51]
**Which generator version are you using?**

```sh
build-generator version
build-generator 0.33.63
asdf            3.3.1
SBCL            2.0.10.0.sbcl-2.0.10.0-badfc73b9
```

**What did you do?**
Generate some distribution

**What happened instead?**
Since updating Jenkins generation fails during the deploy step if the jobs already exist.

e.g. Deleting the jenkins/jobs folder and restarting generates without problems

[consoleText.txt](https://github.com/RDTK/generator/files/6598005/consoleText.txt)

**Comment by scymtym** [comment]
The problem is that the warnings NG plugin versions individual pieces of its data model pretty intricately. The generator must parse and generate particular combinations of versions to make things work. So far, I have not found a better method than periodically adding valid version combinations to a table in the generator.

**Comment by rhaschke** [comment]
I can confirm this issue. Using the most recent build-generator (0.34.8) didn't change.
Generating new jobs doesn't pose an issue, but updating existing (rather old?) ones.

**Comment by scymtym** [comment]
I would have to look at the versions in the serialized Warnings NG configuration. I probably still missed a particular combination.

If either of you still observes the problem, can you attach the console output like @LeroyR did above?

**Comment by rhaschke** [comment]
After an update to Jenkins 2.289.2, I observe this issue once again:
http://colossus.techfak.uni-bielefeld.de:8080/view/config/job/run-build-generator/209/console (you need to be in the TechFak VPN).

Deploying from scratch works, but updating just generated jobs doesn't.
@scymtym, could you add another version combi, please?

**Comment by scymtym** [comment]
> Deploying from scratch works, but updating just generated jobs doesn't.  @scymtym, could you add another version combi, please?

I did that for the version combination from the linked run.

That said, I will have to figure out a proper solution eventually.
